spring.application.name=mel-ecom

spring.h2.console.enabled=true
spring.datasource.url:jdbc:h2:mem:test

project.image=images/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.app.jwtSecret=mySecretKey123912738ih2908jkfwhsw897h23ijuhaqw89eftho
spring.app.jwtExpirationMs=3000000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.mel_demo.security_test=DEBUG
